name: "doc-flow"

services:
  nginx:
    image: nginx:alpine
    container_name: doc-flow-nginx
    restart: unless-stopped
    ports:
      - "4330:80" # port that is allowed in the CEFET network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - frontend
    networks:
      - network-doc-flow

  frontend:
    container_name: doc-flow-frontend
    build:
      context: ./apps/doc-flow-client
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - network-doc-flow

  app:
    container_name: doc-flow-backend
    build:
      context: ./apps/doc-flow
      dockerfile: Dockerfile
      target: app
    expose:
      - "3000"
    networks:
      - network-doc-flow
    depends_on:
      - postgres
    env_file:
      - ./.env

  postgres:
    container_name: doc-flow-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./apps/doc-flow/scripts:/docker-entrypoint-initdb.d
    networks:
      - network-doc-flow

  adminer:
    container_name: doc-flow-adminer
    image: adminer
    ports:
      - "8080"
    networks:
      - network-doc-flow

  migrate:
    container_name: doc-flow-migrate
    build:
      context: ./apps/doc-flow
      dockerfile: Dockerfile
      target: db-actions-build
    networks:
      - network-doc-flow
    depends_on:
      - postgres
    env_file:
      - ./.env
    command: ["bash", "/scripts/database-actions.sh", "migrate"]
    volumes:
      - ./apps/doc-flow/scripts:/scripts

  seed:
    container_name: doc-flow-seed
    build:
      context: ./apps/doc-flow
      dockerfile: Dockerfile
      target: db-actions-build
    networks:
      - network-doc-flow
    depends_on:
      - migrate
      - postgres
    env_file:
      - ./.env
    command: ["bash", "/scripts/database-actions.sh", "seed"]
    volumes:
      - ./apps/doc-flow/scripts:/scripts

  redis:
    container_name: doc-flow-redis
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - network-doc-flow

networks:
  network-doc-flow:
    driver: bridge

volumes:
  pgdata:
